// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using WebApiApplication.Data;

namespace WebApiApplication.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApiApplication.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Products");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Name = "Ekta"
                    },
                    new
                    {
                        Id = 2,
                        Name = "Aarti"
                    },
                    new
                    {
                        Id = 3,
                        Name = "Dhwani"
                    },
                    new
                    {
                        Id = 4,
                        Name = "Shreya"
                    },
                    new
                    {
                        Id = 5,
                        Name = "Manali"
                    },
                    new
                    {
                        Id = 6,
                        Name = "Yukta"
                    },
                    new
                    {
                        Id = 7,
                        Name = "Disha"
                    },
                    new
                    {
                        Id = 8,
                        Name = "Naxi"
                    },
                    new
                    {
                        Id = 9,
                        Name = "Vaishali"
                    },
                    new
                    {
                        Id = 10,
                        Name = "Chetna"
                    });
            });
#pragma warning restore 612, 618
        }
    }
}